language: python

python:
    - 3.3
    - 3.4

before_script:
    - "mysql -e 'DROP DATABASE IF EXISTS test_pymysql; create database test_pymysql  DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"
    - "mysql -e 'DROP DATABASE IF EXISTS test_pymysql2; create database test_pymysql2 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"
    - cp .travis.databases.json tests/databases.json

install:
    - pip install flake8
    - pip install nose
    - pip install coverage
    - pip install .
    - pip install coveralls

script:
  - make cov

after_success:
  - coveralls
