language: python

python:
    - 3.3
    - 3.4
    - 3.5

env:
    matrix:
        - PYTHONASYNCIODEBUG=1
        - PYTHONASYNCIODEBUG=

matrix:
   include:
        - python: 3.3
          env: PYTHONASYNCIODEBUG=1
          addons:
              mariadb: 5.5
        - python: 3.4
          env: PYTHONASYNCIODEBUG=
          addons:
              mariadb: 5.5
        - python: 3.4
          env: PYTHONASYNCIODEBUG=1
          addons:
              mariadb: 10.0
        - python: 3.3
          env: PYTHONASYNCIODEBUG=
          addons:
              mariadb: 10.0
        - python: 3.3
          env: PYTHONASYNCIODEBUG=1
          addons:
              mariadb: 10.1
        - python: 3.4
          env: PYTHONASYNCIODEBUG=
          addons:
              mariadb: 10.1


before_script:
    - sleep 5
    - service mysql status
    - "mysql -S /var/run/mysqld/mysqld.sock -e 'SELECT VERSION()'"
    - "mysql -S /var/run/mysqld/mysqld.sock -e 'DROP DATABASE IF EXISTS test_pymysql; create database test_pymysql  DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"
    - "mysql -S /var/run/mysqld/mysqld.sock -e 'DROP DATABASE IF EXISTS test_pymysql2; create database test_pymysql2 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"

install:
    - pip install -Ur requirements-dev.txt
    - pip install .
    - pip install coveralls

script:
- make cov

after_success:
  - coveralls
